### ISSUE TITLE
Permission denied downloading cache when resource class changed

### ISSUE THREAD

**Issue by aluu4445** [CircleCI-Public/flutter-orb#31]
## What happened:
When I change the resource class on CircleCI for an android-machine executor, the restoring cache step of `flutter/install_sdk_and_pub` is unable to restore the cache due to a permissions issue. It slowly goes through each file in the cache with the same error for 20 minutes+:
```
Found a cache from build 15564 at flutter-3.7.10-arch1-linux-amd64-6_85
Size: 705 MiB
Cached paths:
  * /root/development

Downloading cache archive...
Unarchiving cache...
Skipping writing "root/development/" - mkdir /root/development: permission denied
Skipping writing "root/development/flutter/" - mkdir /root/development: permission denied
...
```

There is a `cache_version` parameter for `install_sdk_and_pub` but looking at the orb source it only gets passed into `install_pub` and not `install_sdk` so there's no way to clear the cache for `install_sdk`:
```
        steps:
            - install_sdk:
                install-location: <<parameters.install-location>>
                version: <<parameters.version>>
            - install_pub:
                app-dir: <<parameters.app-dir>>
                cache-version: <<parameters.app-dir>>
```
## Expected behavior:
There should be a cache_version parameter for `install_sdk` so the cache can be cleared.
If a resource class change causes a cache hit, it should not run into this permission issue.
If it does run into the permission issue it should not slowly go through each files for 20 minutes+, but instead treat it as a cache miss.
