### ISSUE TITLE
Flutter orb install_sdk does not work on Apple silicon M1 macs

### ISSUE THREAD

**Issue by birdthedeveloper** [CircleCI-Public/flutter-orb#34]
## What happened:
When installing flutter sdk using the flutter orb on M1 mac, flutter doctor throws the following error:
```
/Users/distiller/development/flutter/bin/internal/shared.sh: line 239: /Users/distiller/development/flutter/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable
```
I assume this is caused by downloading the wrong CPU architecture SDK - amd64 instead of arm64.

## Expected behavior:

Flutter orb downloads sdk without any problems on M1 macs and without any need to specify CPU architecture.

### Minimal example config.yaml to reproduce the error:

``` YAML
version: 2.1

orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  example:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 15.0.0
    steps:
      - flutter/install_sdk:
          version: 3.13.4
```

## Workaround
Prepend the flutter version with `arm64_` like this:
``` YAML
steps:
  - flutter/install_sdk:
      version: arm64_3.13.5
```
