### ISSUE TITLE
Restoring Cache failed during flutter install

### ISSUE THREAD

**Issue by Anceos** [CircleCI-Public/flutter-orb#39]
## What happened:

**Step Restoring Cache failed**

error computing cache key: template: cacheKey:1:9: executing "cacheKey" at <checksum "./pubspec.lock">: error calling checksum: open /home/circleci/project/pubspec.lock: no such file or directory

then 

**Step Install dependecies**

```
#!/bin/bash -eo pipefail
flutter pub get
```

Expected to find project root in current working directory.

Exited with code exit status 1

`CircleCI received exit code 1`

## Expected behavior:

I should be able to finish installation 

## Additional Information:

```
version: '2.1'
orbs:
  flutter: circleci/flutter@2.0
  android: circleci/android@1.0.3


jobs:
  install_for_android_machine:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.7.6
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: android
workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - install_for_android_machine
```
