### ISSUE TITLE
Add support for `gradle.kts`

### ISSUE THREAD

**Issue by jxstxn1** [CircleCI-Public/flutter-orb#51]
## Describe Request:

Since Version 3.29.X, Flutter creates new Projects using the Gradle Kotlin DSL.
However migrating or adding a new Project to CircleCi is made harder since the `flutter-orb` currently only supports the "old" `.gradle` groovy dsl.

## Examples:
Update to Flutter 3.29.X and create a test project

**Comment by marboledacci** [comment]
HI @jxstxn1 does #54 solves your issue?

**Comment by jxstxn1** [comment]
Hey @marboledacci,
I can't really test this right now since I now face the Issue that the CI falls back to Gradle 8.10 instead of 8.11 which I specified in the `gradle-wrapper.properties`. Therefore I can't fully test it since the CI is failing at `flutter/install_android_gradle_dependencies`

**Comment by marboledacci** [comment]
@jxstxn1 Try restarting your cache_key first, as that's what changed

**Comment by jxstxn1** [comment]
> Try restarting your cache_key first, as that's what changed

@marboledacci  I already bumped the `cache-version` of `flutter/install_sdk_and_pub`, `flutter/install_android_gradle_dependencies` and `flutter/install_android_gem` if that is what you mean

**Comment by marboledacci** [comment]
What error are you getting? I don't see how the orb could be changing your gradle version

**Comment by jxstxn1** [comment]
I don't really understand why the orb is applying `gradle-8.10` either.

<details><summary>The error inside of <b>Installing Android Gradle Plugins</b> is the following</summary>
<p>

```
Welcome to Gradle 8.10!

<removed to keep the error short and clean>

> Task :gradle:compileJava NO-SOURCE
> Task :gradle:compileGroovy NO-SOURCE
> Task :gradle:classes
> Task :gradle:jar

FAILURE: Build failed with an exception.

* Where:
Build file '/home/circleci/project/android/app/build.gradle.kts' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 8.11.1. Current version is 8.10. If using the gradle wrapper, try editing the distributionUrl in /home/circleci/project/android/gradle/wrapper/gradle-wrapper.properties to gradle-8.11.1-all.zip
```

</p>
</details> 

I double checked the `gradle-wrapper.properties` inside of `gradle/wrapper`. This looks fine too
<details><summary>gradle-wrapper.properties</summary>
<p>

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-all.zip
```

</p>
</details> 

I also retried bumping the `cache-version` of `flutter/install_sdk_and_pub` aswell as `flutter_install_android_gradle_depencencies`

<details><summary>Therefore the beginning of my action now looks like</summary>
<p>

```
version: 2.1
orbs:
  flutter: circleci/flutter@dev:44e9277705d1d16f777ff0d17f1b0572386eb1aa
  android: circleci/android@3.1.0

jobs:
  android:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.32.7
          cache-version: v4
      - flutter/install_android_gradle_dependencies:
          cache-version: v4
      - flutter/install_android_gem:
          cache-version: v3
```

</p>
</details>
