### ISSUE TITLE
CircleCI flutter orb unexpected argument: version

### ISSUE THREAD

**Issue by svareniem** [CircleCI-Public/flutter-orb#8]
## Orb version:
1.0.1

## What happened:
I've got the error:
```
Error calling workflow: 'distribute'Error calling job: 'distribute'Error calling command: 'flutter/install_sdk_and_pub'Unexpected argument(s): version
```

## Expected behavior:
It should download and install Flutter version passed as argument version.

## Additional Information:
Yaml file:

```
version: '2.1'
orbs:
  flutter: circleci/flutter@1.0.1
jobs:
  distribute:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 2.8.1
          app-dir: ./app
      - flutter/install_ios_pod:
          app-dir: ./app
      - flutter/install_ios_gem:
          app-dir: ./app
      - run:
          command: bundle exec fastlane ios distribute
          working_directory: ios
workflows:
  distribute:
    jobs:
      - distribute
```
